spring:
  application:
    name: msa-query
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://postgresql-service:5432/cnapp}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASS:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST:redis-service}
      port: ${REDIS_PORT:6379}

server:
  port: 8083
