image:
  repository: ckstj8027/cnapp-agent
  tag: latest
  pullPolicy: Always

# MSA Ingestion 서비스 주소 (릴리즈 이름 'msa' 기준)
server:
  url: "http://msa-ingestion-service:8081/api/v1/ingestion/k8s"

# 인증을 위한 API Key
auth:
  apiKey: "83da2482-30fc-454c-b22f-e0aa0b82af11"

rbac:
  create: true
