spring:
  application:
    name: msa-analysis
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cnappdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka-service:9092}
    consumer:
      group-id: msa-analysis-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      max-poll-records: 5
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.k8s.cnapp.msa.common.dto.IngestionRequestMessage
        request.timeout.ms: 60000
        session.timeout.ms: 45000
        heartbeat.interval.ms: 15000
        max.partition.fetch.bytes: 10485760
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis-service}
      port: ${SPRING_DATA_REDIS_PORT:6379}

server:
  port: 8082
