apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ingestion-service
spec:
  ports:
    - port: {{ .Values.ingestion.service.port }}
      targetPort: {{ .Values.ingestion.service.port }}
  selector:
    app: ingestion
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ingestion
...
