apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
spec:
  rules:
  # host 항목을 생략하여 모든 IP(192.168.56.30 등)로의 접속을 허용합니다.
  - http:
      paths:
      # 1. 백엔드 API 분기
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-query
            port:
              number: 80 # query 서비스의 ClusterIP 포트
      # 2. 프론트엔드 분기
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-front-service
            port:
              number: 80
