apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      # 1. 인증/회원가입 분기
      - path: /api/login
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-auth-service
            port:
              number: 8084
      - path: /api/signup
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-auth-service
            port:
              number: 8084
      # 2. 에이전트 수집 API 분기 (중요! ⭐)
      - path: /api/v1/ingestion
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-ingestion
            port:
              number: 8081
      # 3. 대시보드 조회 API 분기
      - path: /api/v1/dashboard
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-query
            port:
              number: 80
      # 4. 프론트엔드 분기
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-front-service
            port:
              number: 80
