# [명세 준수] PostgreSQL 배포 및 강제 바인딩 PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  # [핵심] 특정 PV를 콕 찍어서 바인딩 (이름 불일치 방지)
  volumeName: {{ .Release.Name }}-postgres-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate # DB는 한 번에 하나만 띄우도록 보장
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.database.image }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.database.dbName }}
            - name: POSTGRES_USER
              value: {{ .Values.database.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.database.pass }}
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
