# [K-Sentry 공식 명세 준수] 모든 인프라 PV 설정 (최종 고정)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: msa-postgres-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual # [추가] SC 충돌 방지
  hostPath:
    path: "/mnt/data/postgres-msa"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: msa-kafka-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/kafka-msa"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: msa-redis-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/redis-msa"
