apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-query-service
spec:
  type: {{ .Values.query.service.type }}
  ports:
    - port: {{ .Values.query.service.port }}
      targetPort: 8083
  selector:
    app: query
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-query
...
