# [K-Sentry 공식 명세 준수] Redis (최종 고정)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-redis-service-master-0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 8Gi
  volumeName: msa-redis-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: storage
              mountPath: /data
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: redis-data-redis-service-master-0
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service # [명세 고정]
spec:
  ports:
    - port: 6379
  selector:
    app: redis
