server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # JSON 파일이나 정적 자산이 없는 경우 404를 반환하여 SvelteKit의 오작동을 방지합니다.
    location ~* \.(json|ico|png|jpg|jpeg|svg|js|css)$ {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
