apiVersion: v2
name: cnapp-msa
description: Helm chart for K8s CNAPP MSA Version (All-in-One)
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: kafka
    version: 26.4.3
    repository: https://charts.bitnami.com/bitnami
  - name: postgresql
    version: 13.2.24
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: 18.6.1
    repository: https://charts.bitnami.com/bitnami
