global:
  namespace: cnapp-msa

ingestion:
  replicaCount: 2
  image:
    repository: cnapp-msa-ingestion
    tag: latest
  service:
    type: ClusterIP
    port: 8081

analysis:
  replicaCount: 3
  image:
    repository: cnapp-msa-analysis
    tag: latest
  service:
    type: ClusterIP
    port: 8082

query:
  replicaCount: 2
  image:
    repository: cnapp-msa-query
    tag: latest
  service:
    type: LoadBalancer
    port: 80

# --- Dependencies Configuration ---

# 1. Kafka (Bitnami)
kafka:
  fullnameOverride: kafka-service
  listeners:
    client:
      protocol: PLAINTEXT
  rbac:
    create: true

# 2. PostgreSQL (Bitnami)
postgresql:
  fullnameOverride: postgresql-service
  auth:
    database: cnapp
    username: postgres
    password: "password"
    postgresPassword: "password"

# 3. Redis (Bitnami)
redis:
  fullnameOverride: redis-service
  auth:
    enabled: false

# --- Microservices Connection Mapping ---
# 템플릿에서 .Values.kafka.bootstrapServers 형식으로 호출하기 위해 구조를 맞춥니다.
kafka_bootstrap_servers: "kafka-service:9092"
database:
  url: "jdbc:postgresql://postgresql-service:5432/cnapp"
  user: "postgres"
  pass: "password"
