global:
  namespace: cnapp-msa

# --- Frontend (SvelteKit) ---
frontend:
  replicaCount: 1
  image:
    repository: ckstj8027/cnapp-front
    tag: latest
  service:
    port: 80

# --- MSA Backend Services ---
ingestion:
  replicaCount: 1
  image:
    repository: ckstj8027/cnapp-msa-ingestion
    tag: latest
  service:
    port: 8081

analysis:
  replicaCount: 1
  image:
    repository: ckstj8027/cnapp-msa-analysis
    tag: latest
  service:
    port: 8082

query:
  replicaCount: 1
  image:
    repository: ckstj8027/cnapp-msa-query
    tag: latest
  service:
    type: ClusterIP
    port: 80

# --- Ingress Settings ---
ingress:
  enabled: true
  className: "nginx"
  host: "" # 모든 호스트/IP 접속 허용을 위해 비워둡니다.

# --- Infrastructure Settings ---
kafka:
  image: apache/kafka:3.7.0
  serviceName: kafka-service
  port: 9092
  controllerPort: 9093

database:
  image: postgres:15
  dbName: cnappdb
  user: postgres
  pass: password
  storage: 1Gi

redis:
  image: redis:7.0-alpine
